### ISSUE TITLE
NPE when running ant over existing install

### ISSUE THREAD

**Issue by joewiz** [joewiz/hsg-project#9]
Using hsg-shell branch of eXist-LTS (basically up to date with the eXist develop branch), I get an NPE when running `ant` from this project over an existing installation at the point when monex is installed. If monex is not yet installed (i.e., if you've run `build.sh clean-default-data-dir` in `$EXIST_HOME`, monex installs without error. 

Steps to reproduce:

- clone eXist develop branch. if you already have one, run `build.sh clean-default-data-dir` to wipe your db.
- clone this repo. run `ant setup` to clone subrepositories.
- start eXist
- run `ant` in this project to build the xars and deploy to eXist
- this should complete without error
- run `ant` again
- the script breaks at the point when deploying monex. 

Below is the log information I've collected:

Here is the console output where `ant` begins to show problems:

```
deploy.install-monex:
     [echo] Installing monex ...

BUILD FAILED
/Users/joe/workspace/hsg-project/build.xml:68: XMLDB exception caught while executing query: Failed to invoke method queryP in class org.exist.xmlrpc.RpcConnection: null
```

Here is the relevant portion of build.xml is where we fetch and deploy monex:

```xml
<target name="deploy.install-monex">
    <echo message="Installing monex ..."/>
    <xdb:xquery uri="${instance.temp}" user="${instance.user}" password="${instance.password}"
                query="repo:install-and-deploy('http://exist-db.org/apps/monex', 'http://demo.exist-db.org/exist/apps/public-repo/modules/find.xql')"/>
</target>
```

Nothing shows in exist.log except this:

```
2015-11-29 17:55:30,777 [eXistThread-41] INFO  (Deploy.java [load]:274) - Retrieving package from http://demo.exist-db.org/exist/apps/public-repo/modules/find.xql?name=http%3A%2F%2Fexist-db.org%2Fapps%2Fmonex&processor=3.0.0 
```

But I do see the following NPE in xmlrpc.log:

```
2015-11-29 17:55:30,393 [eXistThread-43] INFO  (RpcConnection.java [createCollection]:180) - collection /db/hsg-temp has been created 
2015-11-29 17:55:32,824 [eXistThread-41] ERROR (XmlRpcErrorLogger.java [log]:36) - Failed to invoke method queryP in class org.exist.xmlrpc.RpcConnection: null 
org.apache.xmlrpc.common.XmlRpcInvocationException: Failed to invoke method queryP in class org.exist.xmlrpc.RpcConnection: null
	at org.apache.xmlrpc.server.ReflectiveXmlRpcHandler.invoke(ReflectiveXmlRpcHandler.java:129) ~[xmlrpc-server-3.1.3.jar:3.1.3]
	at org.apache.xmlrpc.server.ReflectiveXmlRpcHandler.execute(ReflectiveXmlRpcHandler.java:106) ~[xmlrpc-server-3.1.3.jar:3.1.3]
	at org.apache.xmlrpc.server.XmlRpcServerWorker.execute(XmlRpcServerWorker.java:46) ~[xmlrpc-server-3.1.3.jar:3.1.3]
	at org.apache.xmlrpc.server.XmlRpcServer.execute(XmlRpcServer.java:86) ~[xmlrpc-server-3.1.3.jar:3.1.3]
	at org.apache.xmlrpc.server.XmlRpcStreamServer.execute(XmlRpcStreamServer.java:200) [xmlrpc-server-3.1.3.jar:3.1.3]
	at org.apache.xmlrpc.webserver.XmlRpcServletServer.execute(XmlRpcServletServer.java:112) [xmlrpc-server-3.1.3.jar:3.1.3]
	at org.apache.xmlrpc.webserver.XmlRpcServlet.doPost(XmlRpcServlet.java:196) [xmlrpc-server-3.1.3.jar:3.1.3]
	at org.exist.xmlrpc.RpcServlet.doPost(RpcServlet.java:67) [exist.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:755) [servlet-api-3.0.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) [servlet-api-3.0.jar:?]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684) [jetty-servlet-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:503) [jetty-servlet-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:575) [jetty-security-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429) [jetty-servlet-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:229) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:103) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.exist.http.urlrewrite.Forward.doRewrite(Forward.java:50) [exist-optional.jar:?]
	at org.exist.http.urlrewrite.XQueryURLRewrite.service(XQueryURLRewrite.java:221) [exist-optional.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) [servlet-api-3.0.jar:?]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684) [jetty-servlet-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:503) [jetty-servlet-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:533) [jetty-security-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429) [jetty-servlet-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.server.Server.handle(Server.java:370) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:982) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1043) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865) [jetty-http-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240) [jetty-http-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82) [jetty-server-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696) [jetty-io-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53) [jetty-io-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608) [jetty-util-8.1.17.v20150415.jar:8.1.17.v20150415]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543) [jetty-util-8.1.17.v20150415.jar:8.1.17.v20150415]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.NullPointerException
	at org.exist.xquery.modules.expathrepo.Deploy.eval(Deploy.java:173) ~[exist-modules.jar:?]
	at org.exist.xquery.BasicFunction.eval(BasicFunction.java:70) ~[exist.jar:?]
	at org.exist.xquery.InternalFunctionCall.eval(InternalFunctionCall.java:56) ~[exist.jar:?]
	at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71) ~[exist.jar:?]
	at org.exist.xquery.PathExpr.eval(PathExpr.java:267) ~[exist.jar:?]
	at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71) ~[exist.jar:?]
	at org.exist.xquery.XQuery.execute(XQuery.java:279) ~[exist.jar:?]
	at org.exist.xquery.XQuery.execute(XQuery.java:199) ~[exist.jar:?]
	at org.exist.xmlrpc.RpcConnection.doQuery(RpcConnection.java:250) ~[exist.jar:?]
	at org.exist.xmlrpc.RpcConnection.lambda$null$368(RpcConnection.java:1692) ~[exist.jar:?]
	at org.exist.xmlrpc.RpcConnection$$Lambda$141/1144117595.applyXmlRpc(Unknown Source) ~[?:?]
	at org.exist.xmlrpc.function.XmlRpcCompiledXQueryFunction.apply(XmlRpcCompiledXQueryFunction.java:41) ~[exist.jar:?]
	at org.exist.xmlrpc.RpcConnection.lambda$compileQuery$429(RpcConnection.java:3509) ~[exist.jar:?]
	at org.exist.xmlrpc.RpcConnection$$Lambda$140/1653329033.apply(Unknown Source) ~[?:?]
	at org.exist.xmlrpc.RpcConnection.lambda$queryP$369(RpcConnection.java:1692) ~[exist.jar:?]
	at org.exist.xmlrpc.RpcConnection$$Lambda$139/1824893659.applyXmlRpc(Unknown Source) ~[?:?]
	at org.exist.xmlrpc.function.XmlRpcFunction.apply(XmlRpcFunction.java:45) ~[exist.jar:?]
	at org.exist.xmlrpc.RpcConnection.withDb(RpcConnection.java:3764) ~[exist.jar:?]
	at org.exist.xmlrpc.RpcConnection.withDb(RpcConnection.java:3748) ~[exist.jar:?]
	at org.exist.xmlrpc.RpcConnection.queryP(RpcConnection.java:1662) ~[exist.jar:?]
	at org.exist.xmlrpc.RpcConnection.queryP(RpcConnection.java:3387) ~[exist.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
	at org.apache.xmlrpc.server.ReflectiveXmlRpcHandler.invoke(ReflectiveXmlRpcHandler.java:115) ~[xmlrpc-server-3.1.3.jar:3.1.3]
	... 48 more
 ```

**Comment by joewiz** [comment]
@adamretter I can't tell for sure, but a quick trace of the NPE here seems to point to recent changes of yours in RpcConnection.java - see https://github.com/eXist-db/exist/blame/15ddefc3457d9619b47072a582804469fb51ba09/src/org/exist/xmlrpc/RpcConnection.java especially lines 250 and 1692:

    at org.exist.xmlrpc.RpcConnection.doQuery(RpcConnection.java:250) ~[exist.jar:?]
    at org.exist.xmlrpc.RpcConnection.lambda$null$368(RpcConnection.java:1692) ~[exist.jar:?]

Could you shed any light on this?

**Comment by joewiz** [comment]
Note: I've just updated the description of this issue to clarify how to reproduce.

**Comment by wolfgangmm** [comment]
This should be fixed by my pull request, which also adds more high-level tests to avoid further regressions: https://github.com/eXist-db/exist/pull/843

**Comment by joewiz** [comment]
Wonderful, thank you, Wolfgang.
